### ISSUE TITLE
Problem with IE 11

### ISSUE THREAD

**Issue by KevinDebeil** [Flamenco/really-relaxed-json#1]
Hello,

Very nice job. really-relaxed-json is really great.

I have several problems with IE11. Here are problems and fixes in index.js :

```
    createParser: () => thePackage.RJsonParserFactory.Companion.getDefault().createParser(),
    createParserFactory: () => thePackage.RJsonParserFactory.Companion.getDefault(),

```
changed to 
```
    createParser: function() { return thePackage.RJsonParserFactory.Companion.getDefault().createParser(); },
    createParserFactory: function() { return thePackage.RJsonParserFactory.Companion.getDefault(); },

```

`toJson: function (rjsonString, compact = true) {`
changed to :
```
    toJson: function (rjsonString, compact) {
		if (compact === undefined) {
			compact = true;
		}

```

`toRJson: function (jsonString, compact = true) {`
changed to :
```
    toRJson: function (jsonString, compact) {
		if (compact === undefined) {
			compact = true;
		}

```

`toJs: function (rjsonString, compact = true) {`
changed to : 
```
    toJs: function (rjsonString, compact) {
		if (compact === undefined) {
			compact = true;
		}

```

```
    PrettyPrinter: thePackage.PrettyPrinter,
    Options
```
Changed to : 
```
    PrettyPrinter: thePackage.PrettyPrinter,
    Options : null,
```

**Comment by Flamenco** [comment]
@KevinDebeil Thanks for your feedback!  Can you let me know what your specific error was so it is documented for others that run into the same issue?

**Comment by KevinDebeil** [comment]
Here is a little more feedback :

The error is : Syntax error
on line createParser: () => thePackage.RJsonParserFactory.Companion.getDefault().createParser(),

Internet explorer doesn't support arrow function.

When I fixed arrow function problem, then I had this one :
Expected ')'
on line toJson: function (rjsonString, compact = true) {

Internet explorer doesn't support default value for parameters

**Comment by Flamenco** [comment]
That’s perfect. So our helper code uses ES6 and you are using IE.  I am going to mark this as a feature request and perhaps we will transpile the index file.
