### ISSUE TITLE
[suggestion] Array as a root by default

### ISSUE THREAD

**Issue by Filyus** [Flamenco/really-relaxed-json#10]
I think the format can be improved/relaxed even more if it will support a root array without using of `[` and `]` characters.
For example a such whole RJSON-file:
```
1
second_item
{
  third: item
}
```
will be treated as such JSON-file:
```
[
  1,
  "second_item"
  {
    "third": "item"
  }
]
```

The problem can be with such file:
```
[ 1 2 3 ]
4
[ 5 6 ]
```
but a correct counting of the brackets solves it easily.

**Comment by Flamenco** [comment]
Hello @Filyus.  Thank you for your suggestion.

We decided against this long ago, determining it was "too relaxed".    See http://www.relaxedjson.org/musings/other-considerations.

The reasoning was that 
1. It makes the lists not apparent when using multi-line strings.
2. Invalid input that was not a list but had multiple words would not be caught by the parser.  This would cause a giant text file possibly be parsed as an array.  When the file starts with the '[' token, the invalid syntax is caught immediately.

**Comment by Filyus** [comment]
I wrote the desired format grammar for nearley. You can check it out on [playground](https://omrelli.ug/nearley-playground/).
I didn't add multi-line strings support and probably some another features.

```
@{%

  const moo = require('moo')
  
  let lexer = moo.compile({
      '{': '{',
      '}': '}',
      '[': '[',
      ']': ']',
      ':': ':',
      true: 'true',
      false: 'false',
      null: 'null',
      space: {match: /(?:,\s*|\s*,|\s+)/, lineBreaks: true},
      number: /-?(?:[0-9]|[1-9][0-9]+)(?:\.[0-9]+)?(?:[eE][-+]?[0-9]+)?\b/,
      string: /"(?:\\["bfnrt\/\\]|\\u[a-fA-F0-9]{4}|[^"\\])*"/,
      raw: /[^,"\s]+?\b/,
  })
  
  %}
  
  @lexer lexer
  
  json -> _ (object | array | rootArray) _ {% function(d) { return d[1][0]; } %}
  
  object -> "{" _ "}" {% function(d) { return {}; } %}
      | "{" _ pair (_ %space _ pair):* _ "}" {% extractObject %}
  
  array -> "[" _ "]" {% function(d) { return []; } %}
      | "[" _ value (_ %space _ value):* _ "]" {% extractArray %}
  
  rootArray -> _ value (_ %space _ value):* _ {% extractRootArray %}
    
  stringLike ->
      string {% id %}
    | raw {% id %}
    
  primitive ->
      number {% id %}
      | stringLike {% id %}
      | "true" {% function(d) { return true; } %}
      | "false" {% function(d) { return false; } %}
      | "null" {% function(d) { return null; } %}
  
  value ->
        object {% id %}
      | array {% id %}
      | primitive {% id %}
  
  number -> %number {% function(d) { return parseFloat(d[0].value) } %}
  
  string -> %string {% function(d) { return JSON.parse(d[0].value) } %}
  
  raw -> %raw {% function(d) { return JSON.parse(`"${d[0].value}"`) } %}
  
  pair -> key _ ":" _ value {% function(d) { return [d[0], d[4]]; } %}
  
  key -> stringLike {% id %}
  
  _ -> null | %space {% function(d) { return null; } %}
  
  @{%
  
  function extractPair(kv, output) {
      if(kv[0]) { output[kv[0]] = kv[1]; }
  }
  
  function extractObject(d) {
      let output = {};
  
      extractPair(d[2], output);
  
      for (let i in d[3]) {
          extractPair(d[3][i][3], output);
      }
  
      return output;
  }
  
  function extractArray(d) {
      let output = [d[2]];
  
      for (let i in d[3]) {
          output.push(d[3][i][3]);
      }
  
      return output;
  }
  
  function extractRootArray(d, l, reject) {
	  if (typeof d[1] === 'object' && d[2].length === 0) {
	      return reject;
	  }
	  if (d[3] === null) {
	      return reject;
	  }
    
      let output = [d[1]];
  
      for (let i in d[2]) {
          output.push(d[2][i][3]);
      }
  
      return output;
  }
  
  %}
```

**Comment by Filyus** [comment]
It seems to me that the problem is only with the confusion in the space/comma separators. Maybe allow only the commas. It  will be still relaxed enough for me.
```
1,2 3,4
```

**Comment by Flamenco** [comment]
The commas are already allowed, although optional.
[1,2 3,4]
http://www.relaxedjson.org/docs/converter.html?source=%5B1%2C2%203%2C4%5D&filename=Untitled

**Comment by Flamenco** [comment]
Also, consider this:

```
hello
```

With your suggestion, is it an array, or a string?

**Comment by Filyus** [comment]
> The commas are already allowed, although optional. [1,2 3,4] http://www.relaxedjson.org/docs/converter.html?source=%5B1%2C2%203%2C4%5D&filename=Untitled

I mean different delimiters confuse human understanding.



> Also, consider this:
> 
> ```
> hello
> ```
> 
> With your suggestion, is it an array, or a string?

array, because I don't want to allow a primitive root.

**Comment by Flamenco** [comment]
In that case, how would you indicate a single boolean?

```
true
```

Is that an array of boolean, or a boolean?

This ambiguity and the need to have to special case it one way or another, is exactly why we put it in "too relaxed"

**Comment by Filyus** [comment]
> In that case, how would you indicate a single boolean?
> 
> ```
> true
> ```
> 
> Is that an array of boolean, or a boolean?
> 
> This ambiguity and the need to have to special case it one way or another, is exactly why we put it in "too relaxed"

This is still an array of boolean. For me, there is no confusion.  This is like a DOM, where the root element can't be a string.

I think even empty string must be considered as array of null. One comma is array of two nulls. This is not like JSON, but this is very strict for me.

**Comment by Flamenco** [comment]
Yep so your grammar only allows top level arrays.  And defaults to `[null]`.  I'm going to close this issue because this would not be compatible with JSON.  Its a limited subset of the language, and not a relaxed syntax that can express the same values as the JSON specification.  It cannot take any JSON and go round trip, that being a prerequisite for our standard.
