### ISSUE TITLE
Decimal numbers are converted to integers

### ISSUE THREAD

**Issue by Max98** [Flamenco/really-relaxed-json#4]
is @Flamenco still here? His email does not work.
I'm having a problem when rjson rounding up numbers.

**Comment by Max98** [comment]
I used relaxed-json instead of really-relaxed-json with a slight edit to the source code.

**Comment by Flamenco** [comment]
Hi @Max98 What can i do for you?

Please post your input and expected output and we will have a look.

**Comment by Max98** [comment]
Hello @Flamenco
Basically, if I have a json string 
```{"x": 5.145, "y": 12.558, "z": 5000}```
really relaxed json outputs: 
```{"x": 5, "y": 13, "z": 5000}```

**Comment by Flamenco** [comment]
This is confirmed and will be fixed today. Thank you.

**Comment by Flamenco** [comment]
Fixed in 0.3.1

https://www.npmjs.com/package/really-relaxed-json
