### ISSUE TITLE
Keys and values with empty string do not format to RJSON

### ISSUE THREAD

**Issue by nibk** [Flamenco/really-relaxed-json#5]
Love this library and hope you keep working on it or make the source code available.

I've run into a bug where RJSON can't parse rjson output that it produced:

{
  "name": ""
}

converts to

{
  name:
}

and when is parsed again I see this error:

Expected value or R_CURLY

**Comment by Flamenco** [comment]
Thank you for the bug report.  We will have a look ASAP.

**Comment by nibk** [comment]
Hi Flamenco

Any luck with this issue? Anything I can do to help?

Matt

**Comment by Flamenco** [comment]
@nibk This is going up on the bench for a look tonight.  Have you found other issues in the meantime?

**Comment by Flamenco** [comment]
Confirmed with the following unit test:
```kotlin
    fun testEmptyValueJsonToRjson() {
        val strJson = """{"name":""}"""
        val parser = RJsonParserFactory.getDefault().createParser()
        val rjson = parser.streamToRJsonStream(strJson.byteInputStream())

        assertEquals("""{name:''}""".trimIndent(), rjson.reader().readText())
    }
```
```text
expected:<{[name:'']}> but was:<{[name:]}>
Expected :{name:''}
Actual   :{name:}
```

**Comment by Flamenco** [comment]
@nibk Were you using the `Java` or `Javascript` library.  If `Javascript`, was it `node` or `browser`?

**Comment by Flamenco** [comment]
Fix was published to https://www.npmjs.com/package/really-relaxed-json.

Version 0.3.0

**Comment by nibk** [comment]
Hi Flamenco,

Thanks for looking at this, I was using the Javascript version both in node and the browser.

I have tested 0.3.1 in node and I get the same error:

ParseException: Expected value or R_CURLY

Note that this error occurs when parsing RJSON in order to produce JSON. It's not clear from the unit test or the issue name that this is the case.

Matt

**Comment by Flamenco** [comment]
Can you post a code snippet that produces the error @nibk ?

**Comment by nibk** [comment]
I think maybe I'm misunderstanding this. Based on the fact that the online tool converted this JSON:

`{ name: "" }`

to this RJSON

`{ name: }`

I thought that was a feature of the tool. So I tried converting this RJSON:

`{ name: }`

back to JSON and got an error.

What I think you are saying is that `name:` to represent a key with an empty string value is not valid RJSON and the problem was that JSON -> RJSON should have produced:

`name: ""` and not just `name:`

In which case I should not expect `name:` to convert to this `name: ""`

**Comment by Flamenco** [comment]
The only way to represent an empty string value is to use quotes.  So it is basically a `reserved word`.  The RJSON without quotes around the empty string is not valid.  For example, how would you represent this.

```json
[ "", "", ""]
``` 

If you allowed empty string values to be `nothing`, and no commas, you would get `[ ]`!

The bug was that the generator should never have output an empty string without quotes in the first place.

**Comment by Flamenco** [comment]
BTW, the online tool has not been updated to use 0.3.x yet, so it will still generate faulty RJSON.

**Comment by nibk** [comment]
Thanks for the update.
