### ISSUE TITLE
Tripping on e bareword as exponent symbol

### ISSUE THREAD

**Issue by nibk** [Flamenco/really-relaxed-json#9]
The parser seems to be tripping over an isolated bareword e:

[ a b c d e ]

which produces

[ "a", "b", "c", "d", NaN ]

[ a b c d 'e' ] works fine.

Possibly due to it being interpreted as an exponent symbol such as 2e5

**Comment by Flamenco** [comment]
@nibk I will add a test case to unit test and work on getting a new release out.  Are you using javascript or java client?

**Comment by Flamenco** [comment]
http://www.relaxedjson.org/docs/converter.html?source=%5Be%5D&filename=Untitled

**Comment by Flamenco** [comment]
Fixed in 0.3.2

https://www.npmjs.com/package/really-relaxed-json
